package calibration_test

import (
	"math"
	"testing"

	"crackstation/internal/calibration"
	"crackstation/internal/geometry"
	"crackstation/internal/propagation"
	"crackstation/internal/spectrum"
)

const tol = 2e-2 // synthetic-data recovery within 2%

func blocks() []spectrum.Block {
	return []spectrum.Block{{StressAmp: 60, MaxStress: 100, CyclesPerDay: 200}}
}

func params(c float64) propagation.Params {
	return propagation.Params{
		Geo:      geometry.Edge,
		Width:    0.3,
		Material: propagation.Material{ParisM: 3, ParisC: c, FractureKIC: 5e4, YieldStrength: 1e5},
		Blocks:   blocks(),
	}
}

// Found-only history generated by the propagator with a known C_true must be
// fitted back to C_true.
func TestRecoverCFromSyntheticFoundHistory(t *testing.T) {
	const cTrue, prior = 1.2e-11, 1e-11
	p := params(cTrue)
	a0 := 0.002
	var obs []calibration.Obs
	var xs []float64
	W := propagation.SpectrumWeight(3, p.Blocks)
	for day := 0; day <= 80; day += 20 {
		a, crit, err := propagation.Grow(p, a0, float64(day))
		if err != nil || crit {
			t.Fatalf("grow day %d: a=%v crit=%v err=%v", day, a, crit, err)
		}
		obs = append(obs, calibration.Obs{Found: true, A: a})
		xs = append(xs, W*float64(day))
	}
	f := calibration.Fit(geometry.Edge, 0.3, 3, prior, obs, xs)
	if !f.Calibrated {
		t.Fatal("expected calibrated result")
	}
	if math.Abs(f.C-cTrue)/cTrue > tol {
		t.Fatalf("fitted C=%.4e, true %.4e, rel %.2f%%", f.C, cTrue, 100*math.Abs(f.C-cTrue)/cTrue)
	}
	t.Logf("C_true=%.3e recovered C=%.3e", cTrue, f.C)
}

// Fewer than two found points -> handbook prior, uncalibrated.
func TestPriorWhenLessThanTwoFound(t *testing.T) {
	prior := 1e-11
	obs := []calibration.Obs{{Found: true, A: 0.002}}
	f := calibration.Fit(geometry.Edge, 0.3, 3, prior, obs, []float64{0})
	if f.Calibrated || f.C != prior {
		t.Fatalf("expected prior %v uncalibrated, got %+v", prior, f)
	}
}

// Only not-found records -> prior, uncalibrated.
func TestPriorWhenOnlyNotFound(t *testing.T) {
	prior := 1e-11
	obs := []calibration.Obs{{Found: false, LimitA: 0.003}}
	f := calibration.Fit(geometry.Edge, 0.3, 3, prior, obs, []float64{0})
	if f.Calibrated || f.C != prior {
		t.Fatalf("expected prior %v uncalibrated, got %+v", prior, f)
	}
}

// A "not found" record whose detection limit is incompatible with the
// found-only fast trend pulls C down to the censoring cap.
func TestNotFoundConstraintPullsCDown(t *testing.T) {
	const m, Wd, prior, cFast = 3.0, 0.3, 1e-11, 5e-11
	W := propagation.SpectrumWeight(m, blocks())
	a0 := 0.002
	a1, crit, err := propagation.Grow(params(cFast), a0, 60)
	if err != nil || crit {
		t.Fatalf("grow: a=%v crit=%v err=%v", a1, crit, err)
	}
	a2, crit, err := propagation.Grow(params(cFast), a0, 120)
	if err != nil || crit {
		t.Fatalf("grow: a=%v crit=%v err=%v", a2, crit, err)
	}

	// Unconstrained: three found points recover cFast.
	fUnc := calibration.Fit(geometry.Edge, Wd, m, prior,
		[]calibration.Obs{
			{Found: true, A: a0},
			{Found: true, A: a1},
			{Found: true, A: a2},
		},
		[]float64{0, W * 60, W * 120})
	if math.Abs(fUnc.C-cFast)/cFast > tol {
		t.Fatalf("unconstrained C=%.3e != %.3e", fUnc.C, cFast)
	}

	// NF at day 30 with a tight detection limit: fast growth is impossible.
	limit := a0 * 1.01
	f := calibration.Fit(geometry.Edge, Wd, m, prior,
		[]calibration.Obs{
			{Found: true, A: a0},
			{Found: false, LimitA: limit},
			{Found: true, A: a1},
			{Found: true, A: a2},
		},
		[]float64{0, W * 30, W * 60, W * 120})
	if !f.Calibrated {
		t.Fatal("expected calibrated result")
	}
	if f.C >= fUnc.C {
		t.Fatalf("NF did not pull C down: %.3e vs unconstrained %.3e", f.C, fUnc.C)
	}
	if f.UsedNF < 1 {
		t.Fatalf("expected active NF constraint, got %d", f.UsedNF)
	}
	// The implied crack at the NF date must not exceed its limit.
	q0 := calibration.Phi(geometry.Edge, Wd, m, a0)
	qLim := calibration.Phi(geometry.Edge, Wd, m, limit)
	if f.C*W*30 > (qLim-q0)*(1+1e-9) {
		t.Fatal("fitted C violates the not-found upper bound")
	}
	t.Logf("NF-constrained C=%.3e (fast %.3e), active NF=%d, rms=%.3e", f.C, cFast, f.UsedNF, f.ResidualRMS)
}
